# Generated by Django 2.0.8 on 2018-10-03 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnquiryType',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='inquiry_type',
        ),
    ]
