# Generated by Django 2.0.8 on 2018-09-21 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='center_heading',
            field=models.CharField(blank=True, help_text='Center Column Heading', max_length=20),
        ),
        migrations.AddField(
            model_name='homepage',
            name='center_logo',
            field=models.ForeignKey(blank=True, help_text='Center Column Logo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='center_text',
            field=models.CharField(blank=True, help_text='Center Column Text', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='full_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro',
            field=models.CharField(blank=True, help_text='Small intro about yourself', max_length=300),
        ),
        migrations.AddField(
            model_name='homepage',
            name='left_heading',
            field=models.CharField(blank=True, help_text='Left Column Heading', max_length=20),
        ),
        migrations.AddField(
            model_name='homepage',
            name='left_logo',
            field=models.ForeignKey(blank=True, help_text='Left Column Logo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='left_text',
            field=models.CharField(blank=True, help_text='Left Column Text', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='right_heading',
            field=models.CharField(blank=True, help_text='Right Column Heading', max_length=20),
        ),
        migrations.AddField(
            model_name='homepage',
            name='right_logo',
            field=models.ForeignKey(blank=True, help_text='Right Column Logo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='right_text',
            field=models.CharField(blank=True, help_text='Right Column Text', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='work_intro',
            field=models.CharField(blank=True, help_text='Some words about your work profile', max_length=300),
        ),
    ]
