# Generated by Django 2.0.8 on 2018-10-03 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180921_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='center_text',
            field=models.CharField(blank=True, help_text='Center Column Text', max_length=256),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='left_text',
            field=models.CharField(blank=True, help_text='Left Column Text', max_length=256),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='right_text',
            field=models.CharField(blank=True, help_text='Right Column Text', max_length=256),
        ),
    ]
